app/assets/javascripts/sign_up_async_request.js.erb
config/initializers/client_side_validations.rb

- Add try and catch 
- disable unique validators

fix js errors in console

---

.travis.yml

- Add qa configurations for CI/CD with travis-ci

Set up travis with qa

---

app/assets/javascripts/sign_up_async_request.js.erb
app/assets/stylesheets/signup.css.scss
app/models/user.rb
app/views/devise/registrations/new.html.erb
config/initializers/client_side_validations.rb

- Updating form to enhance accessibility

Accessibility

---

db/schema.rb

- Remove test column from schema. For some reason it got added to the schema when it shouldn't have.

remove test column

---

db/migrate/20180809153347_change_physical_description_to_be_text_in_teacher_sets.rb
db/schema.rb

- Changing the column type of physical_description in the teacher_sets table from string to text.

change string to text

---

app/assets/javascripts/sign_up_async_request.js.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/_navigation.html.erb

- This PR allows voice-over functionality when navigating the form.

add accessibility fixes for screen readers

---

test/integration/user_flow_test.rb

remove end

---

app/models/user.rb
app/views/layouts/_breadcrumb.html.erb

Fix duplicate email validation message and breadcrumb

---

app/models/user.rb

- All first name and last name to have spaces and special characters.

fix first and last name validation

---

app/models/user.rb
app/views/devise/registrations/new.html.erb
test/factories/user_factory.rb
test/unit/user_test.rb

- Add alt_email uniqueness back.

Fix alt email bug

---

app/models/user.rb
test/factories/user_factory.rb
test/unit/user_test.rb

- Add validation for PIN format 
- Patterns such as:  
- 1111
- 9191
- 0008
- 7000
are prohibited.

add validation for pin

---

app/assets/javascripts/sign_up_async_request.js.erb
app/assets/stylesheets/signup.css.scss
app/models/user.rb
app/views/devise/registrations/new.html.erb
test/factories/school_factory.rb
test/factories/user_factory.rb
test/unit/user_test.rb

- Add noscript tag
- Set interval at every 2 seconds, to check if all fields pass validation.

Handle no javascript on form

---

app/models/user.rb

- Validate PIN pattern on create only, not update

Validate PIN on user create only. 

---

db/migrate/20180820191047_ingest_all_nyc_schools.rb
db/migrate/20180821102147_ingest_sierra_code_zcode_matches.rb
db/schema.rb
lib/tasks/ingest.rake

Run the import_all_nyc_schools rake task via a migration.

Import-all-schools on QA & Prod MLN-155

---

app/models/user.rb

This PR sends the school's name and phone number to the Patron Creator Service based on the format specified in the [project's documentation](https://confluence.nypl.org/display/WT/Patron+Creator+Service).

Send school name & phone to Patron Creator Service MLN-202

---

app/admin/schools.rb
app/models/school.rb

This PR addresses Darya's requested changes in https://github.com/NYPL/MyLibraryNYCApp/pull/43

Adding documentation for one method; deleting extra block variable

---

.ebextensions/07_https-nypl-digital-dev.config

This change is already merged to master, but merging it properly into development here.

Adding SSL certificate to MLN load balancer from ebextensions file

---

config/environments/production.rb

- This action will allow the assets to be compiled during a deployment.

change compile from false to true

---

app/assets/javascripts/sign_up_async_request.js.erb

add new status code

---

Gemfile
Gemfile.lock

The second number in the pagination was incorrect; it kept increasing as you change pages.  Only the bottom number should increase.

Fix bug with admin pagination count MLN-238

---

app/assets/javascripts/controllers/HoldNewCtrl.js
app/assets/javascripts/controllers/TeacherSetDetailCtrl.js
app/assets/stylesheets/teacher_sets.css.scss
app/controllers/holds_controller.rb
app/mailers/hold_mailer.rb
app/models/hold.rb
public/templates/holds/new.html
public/templates/teacher_sets/detail.html

- Add error handling if e-mail server fails when sending e-mail to bookops.

add error handling if e-mail service fails

---

app/mailers/hold_mailer.rb

remove break

---

app/assets/stylesheets/scaffolds.css.scss

- Fix's existing bug to show all topic_labels when clicking topic.

Increase max height in order to see all topics

---

app/admin/user.rb

- Update CSV output per ticket - https://jira.nypl.org/browse/MLN-307

update csv file output

---

app/admin/schools.rb
app/models/school.rb
app/views/schools/_activation_links_container.html.erb

The admin can update schools now.  The screenshot below shows the green success message.
I also the word "Active" or "Inactive" to the activate-school button that I made a few weeks ago.  You can see it at the top-right of this screenshot:

Edits to school names not saving in admin MLN-293

---

app/mailers/hold_mailer.rb

- BCC admin's to canceled order's of teacher sets

add bcc for canceled order

---

app/models/book.rb
app/models/books_in_set.rb
app/models/teacher_set.rb
app/models/teacher_set_book.rb
db/migrate/20180924150408_rename_books_in_sets_table.rb
db/schema.rb

Using a standard format for the name of this join table will make it easier to clean up the database.

Rename books_in_sets to teacher_set_books

---

.travis.yml
README.md
app/controllers/api/v1/bibs_controller.rb
config/routes.rb
test/functional/api/v1/bibs_controller_test.rb

Both create and update will come through on the same path, given that the lambda won't be able to tell the difference.

Accept requests for create, update, destroy a teacher set or book MLN-255

---

app/admin/books.rb
app/admin/teacher_sets.rb

Disable ability to modify teacher sets and books MLN-323

---

app/assets/javascripts/controllers/HoldCancelCtrl.js
app/controllers/holds_controller.rb
public/templates/holds/cancel.html

Fix minor bug where a user could re-cancel a canceled teacher_set order.

fix bug where user's can re-cancel orders

---

app/assets/javascripts/controllers/HoldCancelCtrl.js
app/controllers/holds_controller.rb
public/templates/holds/cancel.html

* fix bug where user's can re-cancel orders
* refactor code
* handle cancel bug
* fix spacing
* refactor controller
* add log wrapper

Merge latest from development to QA 

---

app/admin/books.rb
app/admin/teacher_sets.rb

Add links to book and teacher_set titles in admin dash MLN-323

---

app/models/book.rb
config/application.yml

* update url
* add config for test
* add test url

update url (#198)

---

app/controllers/api/v01/bibs_controller.rb
app/mailers/admin_mailer.rb
app/models/book.rb
app/views/admin_mailer/failed_bibs_controller_api_request.html.erb
test/functional/api/v01/bibs_controller_test.rb
test/test_helper.rb

This shows how the test I added in this PR gets routed through the error handling.

Send admin emails when teacher set or book update fails

---

app/controllers/api/v01/bibs_controller.rb
app/models/teacher_set.rb

Added some basic string cleaning to subjects and topics.

Mln 372 fix topics

---

app/assets/javascripts/controllers/TeacherSetDetailCtrl.js
app/controllers/teacher_sets_controller.rb
app/serializers/teacher_set_for_user_serializer.rb
app/serializers/teacher_set_serializer.rb
public/templates/teacher_sets/detail.html

* Updated MLN Set Page With Availability (FE display from MLN DB)

[MLN-405] - added availability count and total count

---

app/assets/javascripts/controllers/TeacherSetDetailCtrl.js
app/controllers/teacher_sets_controller.rb
app/serializers/teacher_set_for_user_serializer.rb
public/templates/teacher_sets/detail.html

As discussed with Stephen this holds count code is not required to show in front page.
Once (MLN-386) discussions finalize  than will strat work on the holds count.

Reverted holds count code

---

app/models/teacher_set.rb
app/views/holds/_list.html.erb

* Checking nil condition for  current user holds count

Merging from Dev to QA

---

app/controllers/settings_controller.rb
app/views/settings/index.html.erb

* Jira link : http://jira.nypl.org/browse/MLN-461

[MLN-461] - Wrong school appears marking a school inactive

---

app/models/user.rb

Reverts NYPL/MyLibraryNYCApp#398

Revert "Merge: dev -> qa, postgres email verification to use index"

---

app/models/user.rb

Reverts NYPL/MyLibraryNYCApp#397

Revert "testing using db indexes", no longer need code change.

---

app/admin/teacher_sets.rb
app/controllers/api/v01/bibs_controller.rb
app/models/teacher_set.rb
db/migrate/20191009151624_rename_teacher_set_subject_to_area_of_study.rb
db/schema.rb

https://jira.nypl.org/browse/MLN-500
https://jira.nypl.org/browse/MLN-501

[MLN-500] - DB migration to change "Subject" & "Topic"

---

Gemfile
Gemfile.lock
config/initializers/lograge.rb

make sure application logs as well as default rails logging are written to application log file

---

app/controllers/schools_controller.rb
app/views/schools/index.html.erb

Reverts NYPL/MyLibraryNYCApp#602

Revert "[MLN-580] Added alphabet anchors to top of Schools list page"

---

app/controllers/schools_controller.rb
app/views/schools/index.html.erb

reverted school code

---

app/controllers/holds_controller.rb

Found a bug when holds new action was not finishing rendering the response body when it should.  There was also a problem with double-rendering on caught exception.
Added incrementally more docs.

added return statements after render json

---

.travis.yml
Gemfile
Gemfile.lock
app/jobs/application_job.rb
app/jobs/poke_model_1_job.rb
bin/delayed_job
config/application.rb
config/environments/local.rb
config/environments/production.rb
config/environments/qa.rb
config/initializers/delayed_job_config.rb
db/migrate/20200727225857_create_delayed_jobs.rb
db/schema.rb
test/jobs/poke_model_1_job_test.rb

Set up the project to be able to use an ActiveJob worker with a delayed_job backend.  Can test by calling "PokeModel1Job.perform_now" from the rails command console.

First ActiveJob delayed_job code

---

app/models/user.rb
test/integration/user_flow_test.rb
test/unit/user_test.rb

And moved methods dealing with barcodes functionality into their own section in the user model, for better code organization.

changed name of method that checks barcode with sierra for clarity

---

.platform/hooks/prebuild/09_react-rails.sh

Added logic to add nodejs and yarn.

Add script to build nodejs and yarn to .platform
