NYPL/MyLibraryNYCApp

- app/views/layouts/_breadcrumb.html.erb
The breadcrumbs now say "Account", similar to when you go to /account
> Edit breadcrumb when users edits their account MLN-146

- .ebextensions/01_cloudwatch_agent_config.config
This PR updates the CloudWatch streaming log configuration to properly reference the application log: `development.log`.
See on development:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/elasticbeanstalk/my-library-nyc-app-development/var/app/current/log/development.log;stream=i-0264c5b15f84ade14;start=2018-08-07T20:09:00Z
> Adds development.log to CloudWatch

- app/models/user.rb
- test/factories/school_factory.rb
- test/factories/user_factory.rb
- test/integration/user_flow_test.rb
- test/unit/user_test.rb
Include the patron's address in the POST request to the Patron Creator Service.
The address data should come from the patron's school.
> Send school's address as patron's address MLN-165

- app/assets/javascripts/active_admin_custom.js
Asset compilation via the Uglifier gem was failing on production.  In this PR, we use an older syntax for JS compilation that will work with the version of JS that Uglifier uses.
This is already merged into Production, so this PR gets it into Dev and eventually it will get picked up in QA (necessary to prevent merge conflicts when QA is merged into Master).
> Use different syntax for JS string interpolation to fix prod

- .ebextensions/07_https-nypl-digital-dev.config
We set up SSL on the load balancer.  Now we're telling elastic beanstalk about the SSL certificate, by putting it into code.
> Add ebextension for ssl

- app/views/devise/registrations/new.html.erb
- There is no need to disable the submit button by default for the following reasons:
1.  Each client side validation will automatically disable the button if the data is incorrectly validated  
2. For the case of receiving an error from the token service or check_email request, the submit button will also be disabled
> form doesn't not need to be disabled

- app/mailers/hold_mailer.rb
- app/models/hold.rb
- app/models/hold_change.rb
- app/views/hold_mailer/status_change.html.erb
- config/environments/local.rb
Previously, if the user didn't enter a reason for cancellation, they didn't receive an email.  We want the email to be sent in both situations.
I also added local.rb because emails weren't being sent without this being set: `config.action_mailer.default_url_options = { :host => 'localhost:3000' }` and without that file, it wasn't set.
I also turned off `send_admin_notification_email` if the user is in a local or development environment.
> Send hold cancellation email even if no reason MLN-236

- Gemfile
- Gemfile.lock
The upper counts in all admin pagination were incorrect (it showed more than the total number of items).
> Fix bug in pagination count MLN-238

- app/admin/user.rb
- app/models/user.rb
- test/unit/user_test.rb
There is a page for adding a new user via the admin dashboard:
The required fields are the ones that are the same from the sign-up-form:
The system automatically assigns a barcode if none is assigned by the admin:
The admin can edit the user:
> Ability to add user via MLN admin interface MLN-279

- app/views/layouts/_timeout.html
IE couldn't handle the XMLHttpRequest format, so I changed it to AJAX.
If you want to test it locally, use this in sessions_controller.rb:
```
def max_session_duration
20.seconds
end
def timeout_warning_duration
10.seconds
end
```
and this line twice in _timeout.html:
```
setTimeout(PeriodicalQuery, (3 * 1000));  //three seconds rather than 5 minutes
```
> Make the timeout check IE compatible

- app/models/book.rb
- app/models/teacher_set.rb
- config/application.yml
- db/migrate/20180926114647_add_bnumber_to_books.rb
- db/migrate/20180926134547_clean_up_books_and_teacher_sets.rb
- db/migrate/20180928145516_add_index_to_teacher_sets_and_books.rb
- db/schema.rb
- lib/catalog_item_methods.rb
- lib/tasks/cleanup.rake
1. Add bnumber to books
2. Index books and teacher sets by bnumber
3. Enforce uniqueness on bnumber in the teacher set and book models and in the indexes
4. Create rake task to do the following:
- delete all duplicate books and teacher sets based on bnumbers (there are no teacher sets with duplicate bnumbers, FYI)
- change the book_id or teacher_set_id of the duplicate associated records (ie holds for teacher sets and teacher sets for books) to match the book or teacher set that wasn't deleted
> Clean up teacher set records MLN-299

- app/controllers/api/v1/bibs_controller.rb
- config/routes.rb
- test/functional/api/v1/bibs_controller_test.rb
I changed the routes now that we're sending teacher sets for create/update and delete in bulk.
I removed the update-book endpoint.
> Remove delete_book endpoint MLN-255

- app/views/admin/_history.html.arb
- app/views/admin/_version.html.erb
Look for "old/new" labels below.  Previously there were two bullet points and it wasn't clear which one was the old version of the attribute and which was the new.
> Adding label for new/old to each changed attribute in a version

- app/controllers/api/v1/bibs_controller.rb
- app/models/book.rb
- app/models/teacher_set.rb
- lib/log_wrapper.rb
- test/functional/api/v1/bibs_controller_test.rb
- test/test_helper.rb
- test/unit/user_test.rb
This PR is for accepting JSON related to teacher sets and books.  We use the `bnumber` to look up the teacher set.  If it exists, we update it; if it doesn't exist, we create it.
We also loop through the ISBNs and create associations to those books through the `TeacherSetBook` table.  If the book doesn't exist, we create it.  We also remove teacher_set_books records for books with an ISBN that is not in the teacher_set's list of ISBNs
> Create and update teacher set records MLN-300, 302, 328

- app/controllers/api/v1/bibs_controller.rb
Tests were passing because they access the parameters differently.  This fixes a bug I noticed when testing the method with Postman.
> Fix set_request_body method in bibs_controller

- app/controllers/api/swagger/swaggerDoc.json
- Add swagger documentation for MyLibraryNYC endpoint.  
- You can test the documentation here: https://editor.swagger.io/
> add swaggerDoc

- app/admin/teacher_sets.rb
- app/assets/javascripts/active_admin_custom.js
- app/models/teacher_set.rb
- app/views/teacher_sets/_availability_links_container.html.erb
- db/migrate/20181018221847_add_admin_availability_to_teacher_sets.rb
- db/schema.rb
On the teacher-set-show page, there is a button in the top-right to change a set from available to unavailable.
On the teacher-set-show page, there is a column with a checkbox for changing availability of any set.  This is particularly useful when using the filters on the right and changing availability of many teacher sets with just one click each.
> Provide teacher set unavailable flag in admin MLN-350

- app/admin/teacher_sets.rb
- app/controllers/api/v01/bibs_controller.rb
- app/mailers/hold_mailer.rb
- app/models/teacher_set.rb
- app/views/admin_mailer/failed_bibs_controller_api_request.html.erb
- app/views/admin_mailer/teacher_set_update_missing_required_fields.html.erb
- app/views/teacher_sets/_availability_links_container.html.erb
- app/views/teacher_sets/_edit_button_container.html.erb
- config/environments/test.rb
Kevin mentioned we need to make total_copies and available_copies editable.
> Make total_copies and available_copies editable

- app/admin/teacher_sets.rb
- app/assets/javascripts/controllers/TeacherSetDetailCtrl.js
- app/models/teacher_set.rb
- app/views/teacher_sets/_availability_links_container.html.erb
- db/migrate/20181018221847_add_admin_availability_to_teacher_sets.rb
- db/schema.rb
When we change a teacher set's `availability` attribute from "unavailable" to "available", the set becomes available in the view.
> Show available button for available teacher sets

- .ebextensions/09_nginx_timeout.conf
This is to prep the new stacks for unified MyLibraryNYCApp. The Nginx timeout was initially added manually. This is to integrate as part of the new elastic beanstalk instances.
> Adding Nginx timeout

- db/migrate/20200323044742_add_index_to_users.rb
- db/schema.rb
we've cleaned up the users table, so there are no more conflicting barcodes.  now we can add the unique restriction to that column, to help data stay clean in the future.
> adding unique index to the users barcode column

- .ebextensions/10_add_logroration.config
This is a preliminary configuration change which can be adjusted.
Adds a file to the .ebextensions configuration to allow logrotate.d to rotate and compress log files for the MyLibraryNYCApp. This will help to alleviate any potential disk space issues by curtailing the growth of log files over time.
All logs are also being sent to CloudWatch.
> Add Log Rotation Configuration

- .ebextensions/001-filesystem.config
This pull request will increase default disk size of all Beanstalk EC2 instances to 64 GB.
The purpose of the root volume size increase is to accommodate upgraded Ruby/React MyLibraryNYC application. 
Success criteria is to be able to see the configuration containing 64 GB for instance disk size, and while within the EC2 instance, seeing that `df -h` would return disk size as 64GB
> Increasing root volume to 64GB.

- .ebextensions/10_add_logroration.config
Moves the log rotation configuration to the hourly directory and updates some of the options for rotation. The current configuration is being applied inconsistently and this attempts to rectify that. When the rotation rules are not applied, the log files continue to grow until the instance is replaced and a new log file is started.
> SEB-2267 Update logrotation to hourly checks
